### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by mouuii** [naiba/solitudes#26]
1.可以借鉴hexo的某些不错的特性
- hexo new post 
  - 本地写作，一键上传
  - 分类，日期，标签都写在文章Front-matter信息中，无须手动配置
    >tags | 标签（不适用于分页） |  
categories | 分类（不适用于分页） |  
   - 数据迁移方便，没有数据库，都是以文件夹格式存储在github上

2.待优化功能
  - blog应该有自己的命令行工具，用于创建文件，上传文件，备份文件。
  - blog应该摒弃关系型数据库，文章内容直接以文件形式存储，参考hexo存储在github上，但是图片资源不应该存储在github上
  - blog应该让用户专注的写文章，能够不联网就能写文章，且不局限用户写文章所用客户端，用户只关心他的文章内容
  - blog界面应该尽最大努力美观，且用户可以切换自己界面

。。。

**Comment by naiba** [comment]
刚换了全文搜索引擎。。

**Comment by mouuii** [comment]
show me the solution!

**Comment by naiba** [comment]
你可以先用一段时间 Hexo 先把博客搭起来

**Comment by naiba** [comment]
1. 博文编辑发布
    1. 使用 Git 仓库作为博文、附件储存
    2. 标签、自定义链接定义在 Markdown 文件中
2. 后端
    1. 监听 webhook 拉取 Git，由 diff URL 进行增量同步到数据库。
    2. 高效索引标签、博文、作者：存到 postgres 数据库。
    3. 主题自定义模板、路由对应渲染路径
    4. 提供公共变量（标题、keyword、description）
    5. 提供模板方法（get_article_by_author、get_article_by_date、etc.）

@mouuii 感觉如何

**Comment by mouuii** [comment]
LGTM
